


INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Afghanistan', 'AF');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Afrique du Sud', 'ZA');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Åland (les Îles)', 'AX');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Albanie', 'AL');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Algérie', 'DZ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Allemagne', 'DE');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Andorre', 'AD');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Angola', 'AO');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Anguilla', 'AI');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Antarctique', 'AQ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Antigua-et-Barbuda', 'AG');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Arabie saoudite', 'SA');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Argentine', 'AR');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Arménie', 'AM');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Aruba', 'AW');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Australie', 'AU');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Autriche', 'AT');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Azerbaïdjan', 'AZ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Bahamas', 'BS');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Bahreïn', 'BH');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Bangladesh', 'BD');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Barbade', 'BB');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Bélarus', 'BY');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Belgique', 'BE');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Belize', 'BZ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Bénin', 'BJ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Bermudes', 'BM');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Bhoutan', 'BT');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Bolivie (État plurinational de)', 'BO');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Bonaire, Saint-Eustache et Saba', 'BQ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Bosnie-Herzégovine', 'BA');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Botswana', 'BW');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Bouvet (l''Île)', 'BV');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Brésil', 'BR');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Brunéi Darussalam', 'BN');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Bulgarie', 'BG');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Burkina Faso', 'BF');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Burundi', 'BI');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Cabo Verde', 'CV');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Caïmans (les Îles)', 'KY');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Cambodge', 'KH');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Cameroun', 'CM');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Canada', 'CA');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Chili', 'CL');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Chine', 'CN');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Christmas (l''Île)', 'CX');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Chypre', 'CY');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Cocos (les Îles) / Keeling (les Îles)', 'CC');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Colombie', 'CO');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Comores', 'KM');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Congo', 'CG');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Congo (la République démocratique du)', 'CD');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Cook (les Îles)', 'CK');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Corée (la République de)', 'KR');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Corée (la République populaire démocratique de)', 'KP');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Costa Rica', 'CR');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Côte d''Ivoire', 'CI');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Croatie', 'HR');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Cuba', 'CU');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Curaçao', 'CW');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Danemark', 'DK');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Djibouti', 'DJ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('République dominicaine', 'DO');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Dominique', 'DM');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Égypte', 'EG');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('El Salvador', 'SV');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Émirats arabes unis', 'AE');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Équateur', 'EC');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Érythrée', 'ER');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Espagne', 'ES');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Estonie', 'EE');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Eswatini', 'SZ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('États-Unis d''Amérique', 'US');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Éthiopie', 'ET');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Falkland (les Îles) / Malouines (les Îles)', 'FK');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Féroé (les Îles)', 'FO');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Fidji', 'FJ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Finlande', 'FI');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('France', 'FR');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Gabon', 'GA');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Gambie', 'GM');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Géorgie', 'GE');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Géorgie du Sud-et-les Îles Sandwich du Sud', 'GS');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Ghana', 'GH');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Gibraltar', 'GI');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Grèce', 'GR');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Grenade', 'GD');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Groenland', 'GL');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Guadeloupe', 'GP');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Guam', 'GU');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Guatemala', 'GT');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Guernesey', 'GG');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Guinée', 'GN');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Guinée équatoriale', 'GQ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Guinée-Bissau', 'GW');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Guyana', 'GY');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Guyane française (la)', 'GF');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Haïti', 'HT');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Heard-et-Îles MacDonald (l''Île)', 'HM');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Honduras', 'HN');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Hong Kong', 'HK');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Hongrie', 'HU');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Île de Man', 'IM');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Îles mineures éloignées des États-Unis', 'UM');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Inde', 'IN');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Indonésie', 'ID');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Iran (République islamique d'')', 'IR');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Iraq', 'IQ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Irlande', 'IE');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Islande', 'IS');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Israël', 'IL');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Italie', 'IT');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Jamaïque', 'JM');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Japon', 'JP');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Jersey', 'JE');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Jordanie', 'JO');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Kazakhstan', 'KZ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Kenya', 'KE');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Kirghizistan', 'KG');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Kiribati', 'KI');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Koweït', 'KW');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Lao, République démocratique populaire', 'LA');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Lesotho', 'LS');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Lettonie', 'LV');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Liban', 'LB');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Libéria', 'LR');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Libye', 'LY');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Liechtenstein', 'LI');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Lituanie', 'LT');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Luxembourg', 'LU');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Macao', 'MO');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Madagascar', 'MG');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Malaisie', 'MY');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Malawi', 'MW');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Maldives', 'MV');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Mali', 'ML');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Malouines (les Îles)', 'FK');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Malte', 'MT');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Mariannes du Nord (les Îles)', 'MP');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Maroc', 'MA');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Marshall (les Îles)', 'MH');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Martinique', 'MQ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Maurice', 'MU');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Mauritanie', 'MR');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Mayotte', 'YT');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Mexique', 'MX');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Micronésie (États fédérés de)', 'FM');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Moldova, République de', 'MD');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Monaco', 'MC');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Mongolie', 'MN');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Monténégro', 'ME');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Montserrat', 'MS');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Mozambique', 'MZ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Myanmar', 'MM');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Namibie', 'NA');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Nauru', 'NR');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Népal', 'NP');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Nicaragua', 'NI');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Niger', 'NE');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Nigéria', 'NG');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Niue', 'NU');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Norfolk (l''Île)', 'NF');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Norvège', 'NO');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Nouvelle-Calédonie', 'NC');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Nouvelle-Zélande', 'NZ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Oman', 'OM');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Ouganda', 'UG');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Ouzbékistan', 'UZ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Pakistan', 'PK');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Palaos', 'PW');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Palestine, État de', 'PS');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Panama', 'PA');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Papouasie-Nouvelle-Guinée', 'PG');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Paraguay', 'PY');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Pays-Bas', 'NL');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Pérou', 'PE');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Philippines', 'PH');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Pitcairn', 'PN');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Pologne', 'PL');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Polynésie française', 'PF');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Porto Rico', 'PR');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Portugal', 'PT');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Qatar', 'QA');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('République centrafricaine', 'CF');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('République démocratique du Congo', 'CD');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('République dominicaine', 'DO');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('République tchèque', 'CZ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Réunion (La)', 'RE');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Roumanie', 'RO');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Royaume-Uni de Grande-Bretagne et d''Irlande du Nord', 'GB');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Russie, Fédération de', 'RU');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Rwanda', 'RW');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Sahara occidental', 'EH');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Saint Barthélemy', 'BL');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Sainte-Hélène, Ascension et Tristan da Cunha', 'SH');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Sainte-Lucie', 'LC');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Saint-Kitts-et-Nevis', 'KN');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Saint-Martin (partie française)', 'MF');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Saint-Martin (partie néerlandaise)', 'SX');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Saint-Pierre-et-Miquelon', 'PM');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Saint-Siège (le)', 'VA');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Saint-Vincent-et-les-Grenadines', 'VC');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Salomon (Îles)', 'SB');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Samoa', 'WS');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Samoa américaines', 'AS');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Sao Tomé-et-Principe', 'ST');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Sénégal', 'SN');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Serbie', 'RS');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Seychelles', 'SC');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Sierra Leone', 'SL');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Singapour', 'SG');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Slovaquie', 'SK');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Slovénie', 'SI');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Somalie', 'SO');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Soudan', 'SD');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Soudan du Sud', 'SS');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Sri Lanka', 'LK');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Suède', 'SE');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Suisse', 'CH');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Suriname', 'SR');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Svalbard et l''Île Jan Mayen', 'SJ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Swaziland', 'SZ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Syrienne, République arabe', 'SY');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Tadjikistan', 'TJ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Taïwan, Province de Chine', 'TW');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Tanzanie, République-Unie de', 'TZ');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Tchad', 'TD');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Terres australes françaises (les)', 'TF');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Territoire britannique de l''océan Indien (le)', 'IO');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Thaïlande', 'TH');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Timor-Leste', 'TL');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Togo', 'TG');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Tokelau', 'TK');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Tonga', 'TO');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Trinité-et-Tobago', 'TT');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Tunisie', 'TN');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Turkménistan', 'TM');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Turks et Caïques (Îles)', 'TC');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Turquie', 'TR');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Tuvalu', 'TV');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Ukraine', 'UA');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Uruguay', 'UY');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Vanuatu', 'VU');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Venezuela, République bolivarienne du', 'VE');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Viet Nam', 'VN');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Wallis et Futuna', 'WF');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Yémen', 'YE');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Zambie', 'ZM');
INSERT INTO pays (nom_pays, abrev_pays) VALUES ('Zimbabwe', 'ZW');
