INSERT INTO unite(libelle_unite) VALUES('g');
INSERT INTO unite(libelle_unite) VALUES('kg');
INSERT INTO unite(libelle_unite) VALUES('c.à.s');
INSERT INTO unite(libelle_unite) VALUES('l');
INSERT INTO unite(libelle_unite) VALUES('cl');
INSERT INTO unite(libelle_unite) VALUES('ml');
INSERT INTO unite(libelle_unite) VALUES('c.à.c');
INSERT INTO unite(libelle_unite) VALUES('sachet');
INSERT INTO unite(libelle_unite) VALUES('sachetnodes');
INSERT INTO unite(libelle_unite) VALUES('boîte');
INSERT INTO unite(libelle_unite) VALUES('boîtes');
INSERT INTO unite(libelle_unite) VALUES('feuille');
INSERT INTO unite(libelle_unite) VALUES('feuilles');
INSERT INTO unite(libelle_unite) VALUES('pincée');
INSERT INTO unite(libelle_unite) VALUES('pincées');
INSERT INTO unite(libelle_unite) VALUES('tranche');
INSERT INTO unite(libelle_unite) VALUES('tranches');
INSERT INTO unite(libelle_unite) VALUES('verre');
INSERT INTO unite(libelle_unite) VALUES('verres');
INSERT INTO unite(libelle_unite) VALUES('boule');
INSERT INTO unite(libelle_unite) VALUES('boules');
INSERT INTO unite(libelle_unite) VALUES('cube');
INSERT INTO unite(libelle_unite) VALUES('cubes');
INSERT INTO unite(libelle_unite) VALUES('filet');
INSERT INTO unite(libelle_unite) VALUES('filets');
INSERT INTO unite(libelle_unite) VALUES('gousse');
INSERT INTO unite(libelle_unite) VALUES('gousses');
INSERT INTO unite(libelle_unite) VALUES('noix');
INSERT INTO unite(libelle_unite) VALUES('noisette');
INSERT INTO unite(libelle_unite) VALUES('noisettes');
INSERT INTO unite(libelle_unite) VALUES('poignée');
INSERT INTO unite(libelle_unite) VALUES('poignées');
INSERT INTO unite(libelle_unite) VALUES('pot');
INSERT INTO unite(libelle_unite) VALUES('pots');
INSERT INTO unite(libelle_unite) VALUES('rouleau');
INSERT INTO unite(libelle_unite) VALUES('rouleaux');
INSERT INTO unite(libelle_unite) VALUES('tasse');
INSERT INTO unite(libelle_unite) VALUES('tasses');
INSERT INTO unite(libelle_unite) VALUES('zeste');
INSERT INTO unite(libelle_unite) VALUES('zestes');
INSERT INTO unite(libelle_unite) VALUES('barquette');
INSERT INTO unite(libelle_unite) VALUES('barquettes');
INSERT INTO unite(libelle_unite) VALUES('bocal');
INSERT INTO unite(libelle_unite) VALUES('bocaux');
INSERT INTO unite(libelle_unite) VALUES('botte');
INSERT INTO unite(libelle_unite) VALUES('bottes');
INSERT INTO unite(libelle_unite) VALUES('branche');
INSERT INTO unite(libelle_unite) VALUES('branches');
INSERT INTO unite(libelle_unite) VALUES('brique');
INSERT INTO unite(libelle_unite) VALUES('briques');
INSERT INTO unite(libelle_unite) VALUES('bûche');
INSERT INTO unite(libelle_unite) VALUES('bûches');
INSERT INTO unite(libelle_unite) VALUES('couteau à lame lisse');
INSERT INTO unite(libelle_unite) VALUES('cagette');
INSERT INTO unite(libelle_unite) VALUES('cagettes');
INSERT INTO unite(libelle_unite) VALUES('caissette');
INSERT INTO unite(libelle_unite) VALUES('caissettes');
INSERT INTO unite(libelle_unite) VALUES('carré');
INSERT INTO unite(libelle_unite) VALUES('carrés');
INSERT INTO unite(libelle_unite) VALUES('cuillère');
INSERT INTO unite(libelle_unite) VALUES('cuillères');
INSERT INTO unite(libelle_unite) VALUES('dose');
INSERT INTO unite(libelle_unite) VALUES('doses');
INSERT INTO unite(libelle_unite) VALUES('entonnoir');
INSERT INTO unite(libelle_unite) VALUES('entonnoirs');
INSERT INTO unite(libelle_unite) VALUES('escalope');
INSERT INTO unite(libelle_unite) VALUES('escalopes');
INSERT INTO unite(libelle_unite) VALUES('étui');
INSERT INTO unite(libelle_unite) VALUES('étuis');
INSERT INTO unite(libelle_unite) VALUES('feuillet');
INSERT INTO unite(libelle_unite) VALUES('feuillets');
INSERT INTO unite(libelle_unite) VALUES('flacon');
INSERT INTO unite(libelle_unite) VALUES('flacons');
INSERT INTO unite(libelle_unite) VALUES('flûte');
INSERT INTO unite(libelle_unite) VALUES('flûtes');
INSERT INTO unite(libelle_unite) VALUES('fond');
INSERT INTO unite(libelle_unite) VALUES('fonds');
INSERT INTO unite(libelle_unite) VALUES('galet');
INSERT INTO unite(libelle_unite) VALUES('galets');
INSERT INTO unite(libelle_unite) VALUES('gobelet');
INSERT INTO unite(libelle_unite) VALUES('gobelets');
INSERT INTO unite(libelle_unite) VALUES('grappe');
INSERT INTO unite(libelle_unite) VALUES('grappes');
INSERT INTO unite(libelle_unite) VALUES('lamelle');
INSERT INTO unite(libelle_unite) VALUES('lamelles');
INSERT INTO unite(libelle_unite) VALUES('morceau');
INSERT INTO unite(libelle_unite) VALUES('morceaux');
INSERT INTO unite(libelle_unite) VALUES('paquet');
INSERT INTO unite(libelle_unite) VALUES('paquets');
INSERT INTO unite(libelle_unite) VALUES('part');
INSERT INTO unite(libelle_unite) VALUES('parts');
INSERT INTO unite(libelle_unite) VALUES('plaque');
INSERT INTO unite(libelle_unite) VALUES('plaques');
INSERT INTO unite(libelle_unite) VALUES('portion');
INSERT INTO unite(libelle_unite) VALUES('portions');
INSERT INTO unite(libelle_unite) VALUES('pot');
INSERT INTO unite(libelle_unite) VALUES('pots');
INSERT INTO unite(libelle_unite) VALUES('rondelle');
INSERT INTO unite(libelle_unite) VALUES('rondelles');
INSERT INTO unite(libelle_unite) VALUES('sachet');
INSERT INTO unite(libelle_unite) VALUES('sachets');
INSERT INTO unite(libelle_unite) VALUES('tablette');
INSERT INTO unite(libelle_unite) VALUES('tablettes');
INSERT INTO unite(libelle_unite) VALUES('talon');
INSERT INTO unite(libelle_unite) VALUES('talons');
INSERT INTO unite(libelle_unite) VALUES('tige');
INSERT INTO unite(libelle_unite) VALUES('tiges');
INSERT INTO unite(libelle_unite) VALUES('tranche');
INSERT INTO unite(libelle_unite) VALUES('tranches');
INSERT INTO unite(libelle_unite) VALUES('troupeau');
INSERT INTO unite(libelle_unite) VALUES('troupeaux');
INSERT INTO unite(libelle_unite) VALUES('verre');
INSERT INTO unite(libelle_unite) VALUES('verres');
INSERT INTO unite(libelle_unite) VALUES('zeste');
INSERT INTO unite(libelle_unite) VALUES('zestes');


INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(1, 1, 0.25);
INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(1, 2, 0.25);
INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(1, 3, 3);
INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(1, 4, 0.4);
INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(1, 15, 0.3);
INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(2, 5, 0.5);
INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(2, 6, 0.4);
INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(2, 7, 0.5);
INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(2, 8, 1);
INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(3, 9, 1);
INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(3, 10, 3);
INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(3, 5, 0.1);
INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(4, 11, 0.25);
INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(4, 12, 1);
INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(4, 13, 1);
INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(5, 14, 0.5);
INSERT INTO quantite(id_recette, id_ingredient, quantite) VALUES(5, 15, 0.2);
 
INSERT INTO ingredient(image_ingredient, allergie_ingredient, nom_ingredient, categorie_ingredient, id_unite) VALUES(LOAD_FILE('\Images\fraise.jpg'), 'Fraise' , 'Fraise', 'Fruits', 1);
INSERT INTO ingredient(image_ingredient, allergie_ingredient, nom_ingredient, categorie_ingredient, id_unite) VALUES(LOAD_FILE('\Images\lait.jpg'), 'Lait/Lactose' , 'Lait', 'Produits laitiers', 2);
INSERT INTO ingredient(image_ingredient, allergie_ingredient, nom_ingredient, categorie_ingredient, id_unite) VALUES(LOAD_FILE('\Images\oeuf.jpg'), 'Oeuf' , 'Oeuf', 'Produits laitiers', 8);
INSERT INTO ingredient(image_ingredient, allergie_ingredient, nom_ingredient, categorie_ingredient, id_unite) VALUES(LOAD_FILE('\Images\farine.jpg'), 'Gluten' , 'Farine', 'Céréales', 1);
INSERT INTO ingredient(image_ingredient, allergie_ingredient, nom_ingredient, categorie_ingredient, id_unite) VALUES(LOAD_FILE('\Images\Carotte.jpg'), 'Carotte' , 'Carotte', 'Légumes', 1);
INSERT INTO ingredient(image_ingredient, allergie_ingredient, nom_ingredient, categorie_ingredient, id_unite) VALUES(LOAD_FILE('C:\Images\Tomate.jpg'), 'Tomate' , 'Tomate', 'Fruits', 1);
INSERT INTO ingredient(image_ingredient, allergie_ingredient, nom_ingredient, categorie_ingredient, id_unite) VALUES(LOAD_FILE('C:\Images\HaricotVert.jpg'), 'Haricot' , 'Haricot vert', 'Légumineuse', 1);
INSERT INTO ingredient(image_ingredient, allergie_ingredient, nom_ingredient, categorie_ingredient, id_unite) VALUES(LOAD_FILE('C:\Images\Poulet.jpg'), 'Poulet' , 'Poulet', 'Viande', 1);
INSERT INTO ingredient(image_ingredient, allergie_ingredient, nom_ingredient, categorie_ingredient, id_unite) VALUES(LOAD_FILE('C:\Images\HaricotRouge.jpg'), 'Haricot' , 'Haricot rouge', 'Légumineuse', 1);
INSERT INTO ingredient(image_ingredient, allergie_ingredient, nom_ingredient, categorie_ingredient, id_unite) VALUES(LOAD_FILE('C:\Images\Porc.jpg'), 'Porc' , 'Porc', 'Viande', 1);
INSERT INTO ingredient(image_ingredient, allergie_ingredient, nom_ingredient, categorie_ingredient, id_unite) VALUES(LOAD_FILE('C:\Images\PorcHache.jpg'), 'Porc' , 'Porc haché', 'Viande', 1);
INSERT INTO ingredient(image_ingredient, allergie_ingredient, nom_ingredient, categorie_ingredient, id_unite) VALUES(LOAD_FILE('C:\Images\Aubergine.jpg'), 'Aubergine' , 'Aubergine', 'Légumes', 1);
INSERT INTO ingredient(image_ingredient, allergie_ingredient, nom_ingredient, categorie_ingredient, id_unite) VALUES(LOAD_FILE('C:\Images\Ail.jpg'), 'Ail' , 'Ail', 'Légumes', 6);
INSERT INTO ingredient(image_ingredient, allergie_ingredient, nom_ingredient, categorie_ingredient, id_unite) VALUES(LOAD_FILE('C:\Images\Orange.jpg'), 'Orange' , 'Orange', 'Fruits', 1);
INSERT INTO ingredient(image_ingredient, allergie_ingredient, nom_ingredient, categorie_ingredient, id_unite) VALUES(LOAD_FILE('C:\Images\Sucre.jpg'), 'Sucre' , 'Sucre', 'Glucide', 1);

INSERT INTO materiel(libelle_materiel) VALUES ('casserole'); 
INSERT INTO materiel(libelle_materiel) VALUES ('cuillere'); 
INSERT INTO materiel(libelle_materiel) VALUES ('couteau'); 
INSERT INTO materiel(libelle_materiel) VALUES ('planche'); 
INSERT INTO materiel(libelle_materiel) VALUES ('poêle'); 
INSERT INTO materiel(libelle_materiel) VALUES ('fouet'); 
INSERT INTO materiel(libelle_materiel) VALUES ('four'); 
INSERT INTO materiel(libelle_materiel) VALUES ('fourchette'); 
INSERT INTO materiel(libelle_materiel) VALUES ('passoire'); 
INSERT INTO materiel(libelle_materiel) VALUES ('batteur électrique'); 
INSERT INTO materiel(libelle_materiel) VALUES ('saladier'); 
INSERT INTO materiel(libelle_materiel) VALUES ('pressoir'); 
INSERT INTO materiel(libelle_materiel) VALUES ('verre');

insert into user(nom_user, prenom_user, pseudo_user, mail_user, date_user, tel_user, password_user) 
VALUES('Achour', 'Souhila', 'sousou', 'sachour@et.intechinfo.fr','2023-05-16','06.34.56.32','password');
insert into user(nom_user, prenom_user, pseudo_user, mail_user, date_user, tel_user, password_user)  
VALUES('Pedra', 'Lea', 'puck', 'pedra@et.intechinfo.fr','2023-05-17','06.65.87.09' ,'mot');
insert into user(nom_user, prenom_user, pseudo_user, mail_user, date_user, tel_user, password_user) 
VALUES('Ding', 'Celive', 'sylvie', 'ding@et.intechinfo.fr','2023-05-18','06.35.12.95','motpass');

insert into pays(nom_pays, abrev_pays) VALUES('France','FRA');
insert into pays(nom_pays, abrev_pays) VALUES('Algerie','DZA');
insert into pays(nom_pays, abrev_pays) VALUES('Portugal','PRT');
insert into pays(nom_pays, abrev_pays) VALUES('Chine','CHN');
insert into pays(nom_pays, abrev_pays) VALUES('Coree du sud','KOR');
insert into pays(nom_pays, abrev_pays) VALUES('Japon','JPN');
insert into pays(nom_pays, abrev_pays) VALUES('Italie','ITA');
insert into pays(nom_pays, abrev_pays) VALUES('Espagne','ESP');
insert into pays(nom_pays, abrev_pays) VALUES('Chili','CHL');
insert into pays(nom_pays, abrev_pays) VALUES('Angleterre','UK');
insert into pays(nom_pays, abrev_pays) VALUES('Etat-Unis','USA');
insert into pays(nom_pays, abrev_pays) VALUES('Inde','IND');
insert into pays(nom_pays, abrev_pays) VALUES('Russie','RUS');
insert into pays(nom_pays, abrev_pays) VALUES('Allemagne','GER');

insert into categorie(libelle_categorie) VALUES('entree');
insert into categorie(libelle_categorie) VALUES('Plat');
insert into categorie(libelle_categorie) VALUES('Dessert');
insert into categorie(libelle_categorie) VALUES('Boisson');

INSERT INTO recette(titre, source, date_recette, categorie_recette, image_recette, nb_personne, temps_prep_recette, temps_total_recette, difficulte, id_user, id_pays, id_categorie) 
VALUES ('Gateau fraise', 'Personne', '2023-05-16', 'Dessert', 'https://', 2, 30, 30, 3, 1, '', 3); 
INSERT INTO recette(titre, source, date_recette, categorie_recette, image_recette, nb_personne, temps_prep_recette, temps_total_recette, difficulte, id_user, id_pays, id_categorie) 
VALUES ('Couscous', 'Souhila', '2023-06-17', 'Plat', 'https://', 4, 30, 30, 2, 1, 2, 2); 
INSERT INTO recette(titre, source, date_recette, categorie_recette, image_recette, nb_personne, temps_prep_recette, temps_total_recette, difficulte, id_user, id_pays, id_categorie) 
VALUES ('Feijoada', 'Lea', '2023-06-17', 'Plat', 'https://', 4, 30, 30, 2, 2, 3, 2); 
INSERT INTO recette(titre, source, date_recette, categorie_recette, image_recette, nb_personne, temps_prep_recette, temps_total_recette, difficulte, id_user, id_pays, id_categorie) 
VALUES ('Aubergine sautée', 'Celive', '2023-06-17', 'Plat', '\Images\aubergineSautee.jpg', 2, 30, 30, 1, 3, 4, 2); 
INSERT INTO recette(titre, source, date_recette, categorie_recette, image_recette, nb_personne, temps_prep_recette, temps_total_recette, difficulte, id_user, id_pays, id_categorie) 
VALUES ('Jus d`orange', 'Personne', '2023-06-17', 'Boisson', 'https://', 4, 0, 30, 0, 2, '', 4); 

INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (1, 1);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (1, 2);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (1, 3);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (1, 4);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (1, 6);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (1, 7);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (1, 9);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (1, 10);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (1, 11);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (2, 1);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (2, 2);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (2, 3);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (2, 8);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (2, 11);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (3, 1);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (3, 3);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (3, 4);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (3, 8);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (3, 11);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (4, 3);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (4, 4);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (4, 5);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (4, 8);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (5, 2);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (5, 3);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (5, 4);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (5, 12);
INSERT INTO recette_materiel(id_recette, id_materiel) VALUES (5, 13);

INSERT INTO etape(id_etape, texte_etape, id_recette) VALUES (1, 'Mélanger dans un saladier les ingrédients les un après les autres', 1); 
INSERT INTO etape(id_etape, texte_etape, id_recette) VALUES (2, 'Laver les fraises et les couper en morceaux.', 1); 
INSERT INTO etape(id_etape, texte_etape, id_recette) VALUES (3, 'Manger le tout.', 1); 
INSERT INTO etape(id_etape, texte_etape, id_recette) VALUES (1, 'Faire cuire le couscous a la vapeur.', 2); 
INSERT INTO etape(id_etape, texte_etape, id_recette) VALUES (2, 'Faire la sauce.', 2); 
INSERT INTO etape(id_etape, texte_etape, id_recette) VALUES (3, 'Melanger les deux.', 2); 
INSERT INTO etape(id_etape, texte_etape, id_recette) VALUES (1, 'Faire cuir la viande pendant 20 minutes.', 3); 
INSERT INTO etape(id_etape, texte_etape, id_recette) VALUES (2, 'Ajouter les haricots.', 3); 
INSERT INTO etape(id_etape, texte_etape, id_recette) VALUES (3, 'Deguster.', 3); 
INSERT INTO etape(id_etape, texte_etape, id_recette) VALUES (1, 'Laver et couper les aubergines et l`ail en cube.', 4); 
INSERT INTO etape(id_etape, texte_etape, id_recette) VALUES (2, 'Faire cuire le tout pendant 20 minutes.', 4); 
INSERT INTO etape(id_etape, texte_etape, id_recette) VALUES (1, 'Laver les oranges et les presser.', 5); 
INSERT INTO etape(id_etape, texte_etape, id_recette) VALUES (2, 'Mettre le jus dans un verre et ajouter le sucre.', 5); 

insert into historique(avis_historique, id_user, id_recette) VALUES(5, 1, 1);
insert into historique(avis_historique, id_user, id_recette) VALUES(3, 2, 1);
insert into historique(avis_historique, id_user, id_recette) VALUES(1, 2, 3);

insert into favoris(id_user, id_recette) VALUES(1, 1);
insert into favoris(id_user, id_recette) VALUES(1, 2);
insert into favoris(id_user, id_recette) VALUES(2, 3);
